### ISSUE TITLE
DRY Items

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#168]
There is a lot of repeated code in the items and we should DRY them up a bit before.  These needs to be available as mixins so they can decorate any classes regardless of superclass hierarchy:

1. Multiple ordered and conditional delegation.  We need to delegate to multiple objects and sometimes only delegate if a condition is try (state exists for example).
2. Generate command methods based on Java Object Enums
3. Generate commands/checks based on java Object Enumbs

Potential syntax:

(1) 
item_delegator :@string_item
item_delegator:  {@string_item.state.to_full_string.to_s}, {@string_item.state?}

(2)
item_command StopMoveType

should generate:
```
def stop
def move
```

(3) 
item_command_state  UpDownType
should generate
```
def up
def up?
def down
def down?
```

**Comment by boc-tothefuture** [comment]
I started doing number one on this list a while ago.. it is hard..

I will work on 2 and 3 which should be much easier.

**Comment by pacive** [comment]
Since we're trying to move away from monkey-patching would it make sense to have a module with common patterns that can be included in each item class? (a base class is unfortunately not possible since some item classes need to subclass Numeric)
Something like
```ruby
module Item
  include Forwardable

  def_delegator :@item, :to_s

  def initialize(item)
    @item = item
  end

  def method_missing(method, *args, &block)
    return @item.__send__(method, *args, &block) if @item.respond_to(method)
    return @item.state.__send__(method, *args, &block) if @item.state.respond_to(method)
  end
```
Also the methods currently in `lib/openhab/dsl/monkey_patch/items/items.rb` would also be in this module.
Other item classes can then just include this and override if necessary.

**Comment by pacive** [comment]
For 2 and 3 it should be possible to check the getAcceptedCommandTypes and getAcceptedDataTypes on the OH item instance to handle this automatically I think?

**Comment by jimtng** [comment]
Most (all?) items can accept REFRESH (RefreshType) command too.
