### ISSUE TITLE
[tests] Allow regex to check log lines

### ISSUE THREAD

**Issue by pacive** [boc-tothefuture/openhab-jruby#249]
Would it be possible to allow regex checks when reading log lines? I noticed e.g that the tests for error logging failed in recet OH versions because they (finally) changed from outputting `<script>` to the full path of the script. I could compensate for this by just testing for a small stub of the line, but would feel better if I could use
```ruby
And It should log /RUBY.test\(.*:8\)/ within 5 seconds
```
instead, to be more precise.

Would this be possible to add?

**Comment by boc-tothefuture** [comment]
We can add regex.  I will say (and it is probably just me) I have trouble reading a regex quickly.  I usually have to decipher it. For example I don't really know what that line above does. I know it looks for RUBY, then any char, then test, then you built a capturing group, but I am not sure what the :8 does.  So, I wouldn't want to see it everywhere, but if we deploy it tactically, no problem.

I will need to look in cucumber to see if we can share the "it should log" between a string and a regex.

Which of our tests broke because they added the full path?  I wouldn't think that would fail something unless we actively were searching for it?

**Comment by pacive** [comment]
It was two tests in the [rule_language.feature](https://github.com/boc-tothefuture/openhab-jruby/blob/858a709b6864dc9e4ccb07a425a42dd049389b93/features/rule_language.feature#L111-L159) where it checks that the stack traces are printed correctly, which was previously just printed as e.g. `RUBY.test(<script>:8)` (for a native java exception, where 8 is the line number in the rule file), but now are printed as `RUBY.test(/full/path/to/file.rb:8)`. Since the test file names are generated randomly, this wouldn't be possible to check for. Bet perhaps this is superfluous to the test and could be removed?

**Comment by boc-tothefuture** [comment]
In this particular case I would submit that we shouldn't be matching line numbers (seems brittle).  Unless we have a specific test that is ensuring line numbers are being emitted (which we don't).  For this particular case (not saying we don't need regx matching) I think we should change the tests to be less brittle.

**Comment by jimtng** [comment]
I was wishing for a regex check on log lines, and capture more of the message. For example:
```
logger.error("oh_item not found in wrapper #{wrapper}")
```

Using regex, I was hoping we could show the name of the faulty wrapper in the cucumber error result. Right now, matching with exact string, I can only match "oh_item not found in wrapper" and that's all that will be shown in the cucumber result.
