### ISSUE TITLE
Object Model Questions

### ISSUE THREAD

**Issue by ccutrer** [boc-tothefuture/openhab-jruby#274]
@boc-tothefuture @jimtng @pacive I want to discuss a bit about the object model before I get going too much farther. Right now the code is split somewhat between monkey patching and wrapping+delegating OpenHAB objects. I haven't looked too much at the history of the repo, but have a spent a good amount of time wading through all the different parts of the code in its current incarnation. My impressions right now are that the code has evolved over time, starting with SwitchItem just using a monkey patch, and then switching to delegation possibly for NumberItem in order to have it inherit from Numeric. Do we have a strong preference either way - wrap _all_ OH classes into plain ruby ones, and delegate as necessary? Go the other way, and work harder to duck-type OH classes so that for example NumberItem can be treated as a Numeric without having to actually wrap and inherit from Numeric? Or go middle of the road and delegate as necessary, but no opposition to monkey patching when it's simpler?

My other major question is about how we're treating Item vs. state. The library is currently mostly written so that you can implicitly treat an item _as_ its state. I.e. `SwitchItem << !SwitchItem`, `DimmerItem << DimmerItem + 5`, etc. Besides that this has left gaps around working with states and commands directly from event objects (which I'm currently working to address), this has also felt unnatural to me. Yes, it makes some code easier to read, but it also introduces some surprises. For example:

```
my_var = SwitchItem # imagine this came from something less obvious, like `items[event.item.name.sub("Scene", "Switch")]`
my_var == SwitchItem # => true # clearly
my_var == ON # => true # huh? I just compared a variable to two completely different classes of object, and that's intentionally acceptable?
```

Man, I keep going back and forth on how I feel about that. My first reaction is always "an Item is _not_ a number. it's a thing that _has_ a number (state), but also has a name, and I can send commands to, or directly update its state." Then I say "well, why isn't just a number that happens to have additional properties like name and label? Well, because it can actually change data type! I.e. it's completely legal for an item to change its state from DecimalType to UnDefType. Which is really weird if we're treating an Item as its state, that the Item has now changed what it is/how it acts, _without_ changing which object it is. But that's really the only valid cross-type state change: to/from UnDefType, which isn't all that different from allowing nil. Except again, it's the Item changing itself, instead of changing which object the state is referring to. So yeah... conflicted.

Finally, and this is a much smaller question in my mind. The library uses `extend` _a lot_. Seems like every object `extend`s itself with everything it's composed of, and so on up the line, all the way to where we `extend` Object. I'm almost certain that means we're polluting the global namespace with lots of internal methods, or methods that should only be callable from inside a `rule` block being globally exposed. Would there be any opposition to eventually cleaning that up? I.e. avoiding `extend` internally somewhat and making some calls more explicit or on private methods or something, and then possibly having a separate module that's extended onto Object with only the public interface (`rule`, `after`, actions, etc.)?

**Comment by boc-tothefuture** [comment]
Great questions @ccutrer 

Monkey patch vs. Delegation: 
You are correct that it started out as a monkey patch, then we hit the Numeric issue and I started moving everything to delegation.  There is certainly a lot of debate in the ruby world about monkey patch vs. delegation.  I think we have delegate to support Numeric and at that point I felt it was important to have consistency.  I am open for debate here. 

Item state: 
I was really fighting hard against the complexity I see in the DSL and even the python library when having to call methods for state and command, etc.  I do find it nice to be able to do things like `DimmerItem << DimerItem + 5`.  `DimmerItem << DimmerItem.state + 5` isn't the end of the world, but in most cases doesn't seem necessary.  I hadn't considered the UnDefType change, which is an odd one.. But for the most part (maybe it is just my cases) I really just treat UnDefType as nil.  Everything is on the table but I would be bummed to lose the expressiveness.

Library:
I agree that we want to limit global namespace corruption, however we also want to be able to access those methods from the ruby code surrounding rule in some cases.  I think we are hindered by how JRuby is setup so that when you are in a rules file you are running against the base object class.  I think we would have to look and see which of the test cases fail when we start limiting scope.

**Comment by ccutrer** [comment]
For item state: I totally get it. I'll admit that I've done comparisons on the OpenHAB DSL _many_ times without adding `.state` and couldn't figure out why my rule didn't work. It doesn't help that errors from the DSL are _awful_.  And gah, the amount of boilerplate and installation steps you have to take for JS and Python (and how often it changes with OpenHAB release, and no doc updates!) is super frustrating. As long as all the operations work against state directly (which I'm working towards), I'm okay with keeping direct usage of Item working. There may be a chance to simplify some things and forward them to state instead of having to implement twice.

**Comment by ccutrer** [comment]
I think I've got enough of an answer for now on all my questions here. Thanks.
