### ISSUE TITLE
ensure_states cucumber tests failing

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#304]
A recent run of ensure_states failed:   https://github.com/boc-tothefuture/openhab-jruby/runs/3934226401?check_suite_focus=true 

There are multiple checks with a timeout of 1 second, those should be increased to a larger number (probably 5 seconds).  Increasing to a larger number should not make tests take longer if they complete quicker and will result in less test failures if the test system/openhab is under load for some reason.

**Comment by ccutrer** [comment]
They actually do take longer, because they are negative assertions (should not log). And the 1 second ones are only after a 5 second one of things that should all happen at once. I guess the state change might take a second for openHAB to actually process the command and it could log things out of order.

**Comment by boc-tothefuture** [comment]
I see a mix of both 'should be' and 'should not be' set to 1 second.
