### ISSUE TITLE
call and document script load/unload for rules files

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#316]
With #314 we now have a sciptLoaded / scriptUnloaded defined on main.  After internal cleanup they should invoke script_loaded, script_unloaded in main if they are defined by the end user so they can do any startup/cleanup they need.  This also needs to be documented.

**Comment by jimtng** [comment]
> After internal cleanup they should invoke script_loaded, script_unloaded in main if they are defined by the end user so they can do any startup/cleanup they need.

I don't see any references to `script_loaded` or `script_unloaded` in the library as of 4.8.3. I tried defining a method called script_loaded but it didn't get executed.

I presume this hasn't been implemented yet?

**Comment by ccutrer** [comment]
it has not. and I would highly recommend it be implemented like `at_exit` is. i.e. in your script you call

```ruby
script_unloaded do
  logger.info("I was started!")
end
```

and `script_unloaded` with be a method _we_ define that just captures the block. then when `scriptUnloaded` is actually call, we just iterate the blocks and call them. this would allow multiple callbacks to exist, and we can even change our internal implementation of timer canceling to use this method and avoid the current tight coupling of `scriptUnloaded` to rules and timers.

**Comment by jimtng** [comment]
I am scratching my head about scriptunload / automatic cancelling of the timers. It doesn't seem to happen reliably, i.e. sometimes the outstanding/active timers get cancelled but sometimes they don't seem to get cancelled.

Here's how to reproduce it: create a script
```ruby
require 'openhab'
# x
t = Time.now
after(1.minute) { logger.error("Time's up #{t}") }
```

I just kept adding x to the comments and re-saving it (so that the file is different and therefore gets reloaded by openhab), before the 1 minute had passed.

In theory, it should cancel all outstanding timers, and you'll only see ONE "Time's up <timestamp>" in the log once you've stopped re-saving the file for a minute. But if you re-save it often enough (and within less than 1 minute), you'll see a bunch of log entries with different timestamps which indicates that those timers didn't get cancelled, and multiple timers got executed.
