### ISSUE TITLE
Exclude certain entities from being pushed into the ruby context by Java library

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#348]
Continues discussion in #341

**Comment by boc-tothefuture** [comment]
@ccutrer - Do you have a list of things that should be excluded?

@jimtng - Do you know how the UI rules work or what is expected in them? 

My concerns about excluding items is based on this message:  https://community.openhab.org/t/jruby-openhab-rules-system/110598/14

**Comment by jimtng** [comment]
> @jimtng - Do you know how the UI rules work or what is expected in them?

I don't have any experience working with the UI rules. I will investigate.

Which items specifically are we thinking of excluding?

**Comment by ccutrer** [comment]
_all_ top level constants. but in particular we're looking for things like PercentType (`Java::OrgOpenhabCoreLibraryTypes::PercentType`), Units, etc.. They should be the ruby proxy class if you `require "openhab"`, or undefined if not. they should _not_ be `class org.openhab.core.library.types.PercentType`, because that's useless. another option would be to silently call `ruby_class` on the incoming global if it responds to it. also be sure to test how they respond at top-level in the rule, and in an `after 1.second {}` block in the rule. note that you may need to import some logging yourself for the cases when you're not doing `require "openhab"`.

**Comment by jimtng** [comment]
Continuing from #435, should HSBType.new be available or not (inside / outside a rule)?

The reason I'm asking, is that it's being used in a cucumber test (color_item.feature). I was trying to use a similar code for my test, and because I was using inside a `run` block, it didn't work.

**Comment by ccutrer** [comment]
It should be available from both. Especially since the OpenHAB docs say that it is available for the preset or whatever it calls it.

**Comment by jimtng** [comment]
> It should be available from both. Especially since the OpenHAB docs say that it is available for the preset or whatever it calls it.

Thanks for the clarification. I will implement a workaround for my test for now, i.e. create an instance variable outside the rule.

**Comment by jimtng** [comment]
I think this is now fixed by #490 and https://github.com/openhab/openhab-addons/pull/12047

**Comment by boc-tothefuture** [comment]
Great work @jimtng
