### ISSUE TITLE
Colors seem hard to work with

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#350]
Often one needs to work with colors in RGB format. 
For example, I need to send an MQTT message to turn on an LED:

```
 state = {state: on_off, brightness: (led.brightness.float_value * 2.55).ceil, color: {r: (led.red.float_value * 2.55).ceil, g: (led.green.float_value * 2.55).ceil, b: (led.blue.float_value * 2.55).ceil}}.to_json
```

**Comment by jimtng** [comment]
we may need PercentType#to_byte 

```
 state = {state: on_off, brightness: led.brightness.to_byte, color: {r: led.red.to_byte, g: led.green.to_byte, b: led.blue.to_byte}}.to_json
```

```
colors_in_bytes do # returns color values in bytes instead of percenttype
 state = {state: on_off, brightness: led.brightness.to_byte, color: {r: led.red, g: led.green, b: led.blue}}.to_json
end
```

**Comment by ccutrer** [comment]
`PercentType#to_byte` seems reasonable to me. it's pretty common for something that accepts 0-100% to actually encode that as 0-255. I have a few things that do that _aren't_ color related that this would be useful for (like sending a message to my holiday lighting to encode the speed of a "chase" pattern is 0-100% encoded as 0-255).

**Comment by jimtng** [comment]
I was just thinking that one day we might see the individual colour elements represented in more than one byte. Perhaps not in this decade...

Although not necessary in this case, a `to_range` converting a PercentType to an arbitrary start - end range could be good. Then we can implement to_byte as to_range(0, 255). As an example, Tasmota's colour temperature values range from 153 to 500.

**Comment by ccutrer** [comment]
-1 on calling it to_range, since that would imply it should return a `Range` instance. but a `scale` method, _taking_ a Range, and returning an value between that range would be appropriate. only question is do we return a BigDecimal from that, or always an integer? the does to_byte need to be `scale(0..255)` or `scale(0...256).to_i` (notice the differing number of dots in the range to indicate if it should be include or exclude the top of the range)

**Comment by jimtng** [comment]
> -1 on calling it to_range, since that would imply it should return a `Range` instance.

oops!



> does to_byte need to be `scale(0..255)` or `scale(0...256).to_i`

Could we deduce the type based on the range elements? i.e. 0...256 vs 0...256.0

In any case it was just a thought. I can't think of where I'd need a range/scale other than colours.

**Comment by ccutrer** [comment]
oh yeah, that's a good point on deducing the type. another use would be with volumes. openhab likes to represent it with PercentType, but often a device actually supports something like -70dB to +10dB. It actually drives me nuts because my receivers are like that, and I'm familiar with the dB scale because that's what the receiver shows, but in basic UI when I'm press-and-holding to adjust it shows the percent (but I have a transform on the item to show the proper dB value when it's not being changed).

**Comment by boc-tothefuture** [comment]
Should we support `scale` and `to_byte` which just calls `scale(0..255)` ?

**Comment by ccutrer** [comment]
that's my vote

**Comment by boc-tothefuture** [comment]
@ccutrer do you want to implement? Do you have a mental picture of how to build it?

**Comment by ccutrer** [comment]
I'd be happy to, but it's not my first priority. the file watcher breaking is really killing me and my desire to work on anything openhab related, so if I get some time to do stuff that'll be my first priority. so anyone else feel free to pick it up in the meantime.
