### ISSUE TITLE
Comparisons fail when comparing a number with units to one without

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#352]
I don't think this was the original behavior?  I think when we compared to a number without units before we made the quantity type that had units become dimensionless for the compare operation.

Currently it throws an exception:
```
2021-10-30 15:30:47.774 [TRACE] [nhab.core.library.types.QuantityType] - (Java::OrgOpenhabCoreLibraryTypes::QuantityType) 100 <=> 465.3 lx (Java::OrgOpenhabCoreLibraryTypes::QuantityType)
2021-10-30 15:30:47.775 [ERROR] [rulesupport.shared.simple.SimpleRule] - Can not compare incompatible units. (Java::JavaLang::IllegalArgumentException)
In rule: Turn on light due to motion
org.openhab.core.library.types.QuantityType.compareTo(org/openhab/core/library/types/QuantityType.java:245)
jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:62)
jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)
org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:456)
org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:317)
RUBY.<=>(/etc/openhab/automation/lib/ruby/gem_home/gems/openhab-scripting-4.8.1/lib/openhab/dsl/types/quantity_type.rb:53)
org.jruby.RubyComparable.<(org/jruby/RubyComparable.java:207)
org.jruby.RubyComparable$INVOKER$s$1$0$op_lt.call(org/jruby/RubyComparable$INVOKER$s$1$0$op_lt.gen)
org.jruby.RubyNumeric.unwrapCoerced(org/jruby/RubyNumeric.java:629)
org.jruby.RubyNumeric.coerceRelOp(org/jruby/RubyNumeric.java:616)
org.jruby.RubyFixnum.op_ltOther(org/jruby/RubyFixnum.java:1142)
org.jruby.RubyFixnum.op_lt(org/jruby/RubyFixnum.java:1123)
org.jruby.RubyInteger$INVOKER$i$1$0$op_lt.call(org/jruby/RubyInteger$INVOKER$i$1$0$op_lt.gen)
org.jruby.RubyNumeric.unwrapCoerced(org/jruby/RubyNumeric.java:629)
org.jruby.RubyNumeric.coerceRelOp(org/jruby/RubyNumeric.java:616)
org.jruby.RubyFixnum.op_ltOther(org/jruby/RubyFixnum.java:1142)
org.jruby.RubyFixnum.op_lt(org/jruby/RubyFixnum.java:1123)
RUBY.<main>(/etc/openhab/automation/jsr223/ruby/personal/esp_home.rb:20)
org.jruby.RubyBasicObject.yieldUnder(org/jruby/RubyBasicObject.java:1778)
org.jruby.RubyBasicObject.instance_exec(org/jruby/RubyBasicObject.java:2694)
org.jruby.RubyBasicObject$INVOKER$i$0$3$instance_exec.call(org/jruby/RubyBasicObject$INVOKER$i$0$3$instance_exec.gen)
RUBY.process_trigger_task(/etc/openhab/automation/lib/ruby/gem_home/gems/openhab-scripting-4.8.1/lib/openhab/dsl/rules/automation_rule.rb:332)
RUBY.process_task(/etc/openhab/automation/lib/ruby/gem_home/gems/openhab-scripting-4.8.1/lib/openhab/dsl/rules/automation_rule.rb:290)
```

I think the old behavior is the appropriate one. If one items is missing units do a dimensionless compare. 
@ccutrer @jimtng ?

**Comment by ccutrer** [comment]
can you give more context of where this is happening (ruby code, and probably the Item definitions being accessed)? Java units are pretty strict that you can't do anything with them. Units::ONE isn't really "dimensionless" as much as it is "a dimension that's not used for anything else". we do abuse that internally to get thing likes `10 - QuantityType.new(10, Units::FAHRENHEIT)` working because we get a coerce call before we know what operation is being performed, and we don't necessarily want to implicitly convert it to 10º yet, because we might be doing multiplication.

I don't think implicitly dropping the units for Units::ONE quantities is bad; it might make perfect sense. I just don't want to necessarily do it if it's an obvious abuse of the API, and we can keep our internal abuse of Units::ONE as an implementation detail.

**Comment by boc-tothefuture** [comment]
@ccutrer 
I had a unit defined as type 'lux' and then I did a comparison against a number.

So:
```
Number:Illuminance Office_Lux "Office Lux [%.1f lx]"  (ESPEnvironmentals) 
```

Then I did a comparison:
```
  Office_Lux < 100
```

**Comment by ccutrer** [comment]
okay, I thought that might be the case. I haven't used dimensions other than Number:Temperature yet, since it hasn't really mattered. And now I see that the `lx` is LX in your original stack trace, _not_ the number one. I'm a little confused on how 100 ended up on the left side of the <=> operator (are you sure there it wasn't that way originally?). but yes, we should definitely change it internally from Units::ONE to the same unit for such a case, and you should be able to do both `Office_Lux < 100` or `100 > Office_Lux`.

I was a bit worried cause I know OpenHAB+MQTT has some serious issues being discussed on the forum around units that sometimes a dimensioned number item can end up with its state being a DecimalType, not a QuantityType. I was wondering if maybe a similar thing was happening that it was ending up with a state of QuantityType with the unit being ONE. Looks like not.

are you hoping I can find some time to fix this?

**Comment by ccutrer** [comment]
I'm only able to reproduce in cucumber with `100 > Office_Lux` and not `Office_Lux < 100`. But it's the right error. Digging into a fix now.
