### ISSUE TITLE
Getting a related item

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#370]
A very common pattern in my rules is to get another item of a similar name, e.g.

```ruby
triggered do |item|
  event_data = items[item.name.sub '_LastMotionType', '_EventData']`
```

Is there a way (or should we even) make this process somewhat easier? I understand that this would rely on some sort of naming pattern.

**Comment by jimtng** [comment]
I'm thinking something like this but not too sure about the name

```ruby
event_data = item.sibling('_EventData')
```

**Comment by ccutrer** [comment]
I think it's something to explore.  Ideally I think I'd want to be able to do something like `GreatCans_Scene.dimmer_item` (get the dimmer associated with the scene controller on the same switch), or `GuestBathShade_Rollershutter.window_contact`, but there isn't always a 1:1 mapping like this (window_contact might be a door_contact, or sometimes it might not have one, or some windows there are multiple shades that I also have to remove Blackout or Roman from the shade name to get to the window. It seems the only way to get what I really want would be to let you declare some sort of mappings (as a hash), then you could use a default proc to do more custom stuff. But is all that actually going to be much less code than a couple of sub calls? Maybe.

**Comment by boc-tothefuture** [comment]
I agree that an "association" system is needed but I am not sure what that looks like. 
I have been doing mine with hashes because:
1. I don't like name based associations because they are fragile 
2. More importantly, if they are done inside of a rule they break during rule execution not during rule processing.

**Comment by pacive** [comment]
If I would implement something like this I would use Item metadata. Then the code would look like:
```ruby
event_data = items[item.meta[eventDataItem]]
```
IMHO this offers much more flexibility than using the item names to find related items.

**Comment by jimtng** [comment]
I'm closing this because there doesn't seem to be an elegant way of doing it, and it's not a critically needed feature, since it can be achieved in many other ways.

**Comment by ccutrer** [comment]
so with my latest two PRs (plus @ktgeek's), it doesn't completely address it, but there _is_ the possibility of using the things to get related items.

I.e. I have a bunch of zwave dimmers that I often get from the scene channel triggering a rule to get to the main dimmer channel. This could be rewritten now as:

```
changed gSceneChannels.members, to: 1.3 do |event|
  dimmer_item = event.item.thing.channels["switch_dimmer"].item
  dimmer_item.ensure << 100
end
```

And the entire `thing.channels["switch_dimmer"].item` could be a great candidate to refactor into:

```
class GenericItem
  def related_item(channel)
    thing.channels[channel].item
  end
end
```

Unfortunately, this won't always work for me for things that have a similar interface, but different backings. I.e. I have a couple different brands of receivers, and the channel for "current input" has a different ID depending on if it's Onkyo, Pioneer, or Anthem. All of which my "receiver turned off, go turn off the current input" rule want to access.

**Comment by jimtng** [comment]
Having item.thing.channels[...].item will be quite useful so creating the `related_item` would be nice. Should we reopen this issue?

BTW would thing.channels[...].item work when multiple items are linked to the same channel?

**Comment by ccutrer** [comment]
> BTW would thing.channels[...].item work when multiple items are linked to the same channel?

It will return the first item. You can use `items` if you want all of them.

**Comment by jimtng** [comment]
> And the entire `thing.channels["switch_dimmer"].item` could be a great candidate to refactor into:
> 
> ```
> class GenericItem
>   def related_item(channel)
>     thing.channels[channel].item
>   end
> end
> ```

how about this, so it looks in related channels first, but also in metadata if no related channels are found...

```
class GenericItem
  def related_item(id)
    thing.channels[id].item || items[item.meta[id]&.value]
  end
end
```

**Comment by ccutrer** [comment]
Perhaps we should be following the semantic model that OH3 pushing quite hard, by making these actions easily accessible: https://www.openhab.org/docs/configuration/actions.html#semantics. I could also imagine a few other helpers:

 * `equipment` - if a `location?`, returns all members of the group that `equipment?` returns true (otherwise call `super` which will return the Equipment this item belongs to)
 * `points` - return all members of the group that `point?` returns true, but also wrap it as a lazy hash so you can access it as a hash passing in a `Point` and/or `Property` (or their subclass). So in my receiver example, to get from the input item to the power item it would `InputItem.equipment.points[Switch]` (where Switch is https://www.openhab.org/javadoc/latest/org/openhab/core/semantics/model/point/switch, though we possibly want to support just passing in a symbol, and look up the actual class for them).
