### ISSUE TITLE
Timed commands cancel incorrectly when device provides update after command

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#408]
Some bindings (such as my light system) send an update after the end device reports its status back.  This is causing my timed commands to self-cancel when they should not.

Options:
1. Ignore updates for some duration
2. Add cancel handler before command is sent and have it ignore the first update

other ideas?

**Comment by jimtng** [comment]
Some things, like xiaomi aqara door sensor, sends regular status updates even when the status hasn't changed. This is why I had a mild objection with the timed commands cancelling its timer on status updates. However I haven't quite figured out the best way to deal with it.

**Comment by jimtng** [comment]
Another case: I have many tasmota devices. I poll their status every X minutes in case they got shut down (e.g. a smart bulb being turned off on the wall). I know I should be using the MQTT LWT to handle this scenario, but I haven't quite perfected how the whole thing works, so for now I'm happy with the polling solution.

As a result, my light bulb might receive status updates due to this regular polling.

As I understand it, your scenario involves a door sensor issuing a timed command to turn on a light. However, you also have a manual switch on the wall, which normally sends a command to turn on that light. So when that light is already turned on by the timed command (by the door sensor), you want to be able to press the switch on the wall, to cancel the timed command. Is that right?

**Comment by boc-tothefuture** [comment]
I have it working with a "settle time".  However, I think the perhaps that use case is not the default use case and canceling because of update to item should be optional.

Right now we have:
`for:` and `on_expire:`

I would like to only have one more option that encapsulates both we want it to cancel when updates and you can provide an optional settle time.  

Not sure what that is however.

**Comment by boc-tothefuture** [comment]
To answer your use case question. Sometimes it is driven by a door sensor. But where I get into trouble is if say when you come downstairs in the morning and lights are automatically dimmed to a percent, then you go to a room and turn the lights on or adjust the percent.  If they turn off after that (seemingly randomly) it annoys people.

**Comment by boc-tothefuture** [comment]
Another possibility is to auto cancel on change instead of update.  That may pick up the majority of use cases.

**Comment by boc-tothefuture** [comment]
I am dog folding a version that cancels on change instead of update.  So far so good.
