### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#42]
Currently the README is getting very very long. It's a bit tricky to navigate and grasp the structure. A structured documentation similar to openhab-helper-libraries might be nice to have.

**Comment by boc-tothefuture** [comment]
Additionally it would be good to have the examples pulled directly somehow from the tests.  As you have seen, those can get out of sync when things change.

**Comment by boc-tothefuture** [comment]
For this story we need to look into:
1. Which theme to use.  I am most familiar with [Just the docs](https://pmarsceill.github.io/just-the-docs/). I considered using the same system openhab-scripters uses but it appears to be very custom (big bash script) rather than just using the native Jekyll / GitHub pages stuff.
2. How do we get the YARD documentation available in the same pages site but different link.
3. How do we get or integrate the living documentation we have in cucumber tests into the main documentation.  [Pickles](https://www.picklesdoc.com/#example_output) will generate the documentation.  But how do we merge that with just the docs? Or is just the docs mostly stubs that points to the pickles live documentation?

**Comment by boc-tothefuture** [comment]
@jimtng Can you take a look [here](https://boc-tothefuture.github.io/openhab-jruby/). That is the beta new docs site.  Let me know what you think or if you spot anything that needs changes before I release it.

**Comment by jimtng** [comment]
Awesome! I love it.

Suggestions, mainly related to the content:
In the document structure it currently has "Rules" then under Rules, you have various triggers. I think those triggers should be under "Triggers" section.

Another thing, while not relevant to the structure, I can't help but notice a misspelling "Othewise" under "Execution" section.

So how does this get generated? Is it automatically extracted from README every time there's a commit on README.md?

**Comment by boc-tothefuture** [comment]
Thanks for the review!  I made the changes you suggested.  

It is generated automatically by GitHub using a technology called Jekyll which is how by default GitHub pages are rendered. The sections are broken into separate documents now in the docs folder and GitHub is configured to look there.
