### ISSUE TITLE
File watch / change trigger

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#426]
Do we want to implement a file watch trigger?

Use case: @boc-tothefuture's sitemap template system - regenerate the sitemap automatically

For me, I have been playing with DeepStack and I have a directory structure to store people's photos for face recognition. I want to automatically register any new photos on DeepStack

**Comment by boc-tothefuture** [comment]
I have been thinking about that.  

Couple of things to consider:
1. Jython talked about it - but I don't think they ever implement it.
2.  There is a binding that notifies on new files (but not changes).  I was wondering if it would be better to PR against that for notifications?  But I haven't looked at the code.


In my local code I have already moved to using the java watcher API for native notification for file changes.  I am still polling for notifications on the watcher, but that is  lightweight since it doesn't poll the files for changes.  The difficulty is that if you don't want to poll, then you need to make a thread and interrupt when the system shuts down or rules file is removed.

**Comment by boc-tothefuture** [comment]
Jython does have a directory trigger: https://openhab-scripters.github.io/openhab-helper-libraries/Python/Core/Packages%20and%20Modules/triggers.html

However, the implementation I used in it had the issue where it uses the underlying watcher in OpenHab, so if you watch the same directory as OpenHab is watching them OpenHab no longer gets notified of changes.

**Comment by boc-tothefuture** [comment]
Looks like the multi watcher thing has been resolved: https://github.com/openhab/openhab-core/pull/2467

And, jython changed their implementation of how they watch directories.  They create their own abstractwatch instance.  Looks fairly straightforward: https://github.com/openhab-scripters/openhab-helper-libraries/blob/master/Core/automation/jsr223/python/core/components/100_DirectoryTrigger.py

**Comment by boc-tothefuture** [comment]
In the jruby version I don't think we would need a new keyword.  `changed` could be extended so if you passed it a directory path it used a directory watch trigger.

**Comment by ccutrer** [comment]
While it's technically possible to overload on type, let's think about does `changed` really make sense for monitoring files? It can for existing files, but not so much describing new or deleted files - which presumably you would want to monitor for, but the run block will likely want to distinguish between the 3 (or maybe 2, if you guarantee a changed files shows up as a delete then a create). Then beyond that, is `String` the type we want? Are we confident we'll have no other use for a `String` with `changed`? Perhaps a `Pathname` would be better?

I don't have an immediate answers for the above, just want to make sure we think about them. Just because we _can_ do something in some way, and it seems slick at the moment, doesn't mean we _should_.

**Comment by boc-tothefuture** [comment]
Agree with the above and it will always be a challenge to balance new keywords with overloading existing key words.  

One thing to add, however, you are monitoring directories not files.  An add/change or delete is a change to that directory.  

But if that isn't clear to everyone maybe the best thing is a new keyword called "directory", then it's clear what it is you are triggering off of.

Plus, you are right as we will probably want to provide options around the trigger such as glob, change type, etc.

**Comment by boc-tothefuture** [comment]
FYI - I have started an implementation and will share for review when I can.

**Comment by jimtng** [comment]
> Looks like the multi watcher thing has been resolved: [openhab/openhab-core#2467](https://github.com/openhab/openhab-core/pull/2467)

No it's not yet resolved - that PR was closed, not merged.
