### ISSUE TITLE
Reinstate optimized karaf client for cucumber

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#465]
#462 removed the optimized karaf client that reused the open input/output from the karaf client.  This was removed to because tests related to installing features were failing on OH 3.2.  With the release of 3.2 and some more users looking at JRuby and the libraries it was important to have a stable build, therefore this optimization was commented out.

**Comment by jimtng** [comment]
Are we able to tackle this now? What was the main cause for the optimised client to fail?
How much speed up do we get with the optimised client?

**Comment by boc-tothefuture** [comment]
I am not sure what caused it to fail on 3.2.  I haven't noticed a large decrease in test speed but I think @ccutrer saw a big jump in test speed when he implemented it.

**Comment by ccutrer** [comment]
Iirc the speed up was ~0.5s per karaf call, which depends on what the test is doing. So not huge, but noticeable overall. The bigger one was if the java implementation implements file watching by polling (java for OS X at the time), it takes up to 20s every time a rules file is written, so forcing it to reload immediately (via a karaf call!) helped immensely. That might not matter now either - I now have an M1 Mac, and had to get a newer java than the basic Oracle JRE in order to run latest OpenHAB and I think it actually watches the filesystem instead of polling.

**Comment by jimtng** [comment]
Resolved by #549
