### ISSUE TITLE
change __conf__ to OPENHAB_CONF ?

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#528]
Should we change `__conf__` to `OPENHAB_CONF`? IMO, the latter is more self explanatory.

**Comment by ccutrer** [comment]
I'd prefer something like OpenHAB.conf_root. I didn't notice `__conf__`, and yeah, that's terrible. Double underscore-wrapped identifiers generally means "internal, do _not_ use" or "this is named this way to absolutely avoid a naming conflict" (i.e. `Object#__send__` is an alias for `Object#send` for "send a message to an object" because of `Socket#send` (or any other use of `send`))

**Comment by boc-tothefuture** [comment]
__conf__ matches `__FILE__` and `__dir__` neither of which are deprecated in ruby.

**Comment by ccutrer** [comment]
Indeed. But `__FILE__` is not specific to any particular library -- it's part of the language. Other software puts their directories on their objects. For example, `Rails.root`.

**Comment by jimtng** [comment]
How about `OpenHAB.conf` ?
