### ISSUE TITLE
Consider returning Java.time.Duration instead of our own Duration class

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#86]
Some details in this comment:  https://github.com/boc-tothefuture/openhab-jruby/pull/49#discussion_r563847918

**Comment by jimtng** [comment]
I started playing around with this task, and for the most part it was quite easy and straight forward to do. The only thing I'm not yet certain about is the conversion from duration to cron. As it is, it would be limited to a duration of 1-60 seconds to create a cron of every N seconds up to 59 seconds, and for 60 seconds, create a cron of every minute.
Then from there, we can create a cron of every N minutes, up to 59 minutes, then on to hours.

However, when a duration of 61 seconds is specified, presumably wanting a job done every 61 seconds, it doesn't translate to a cron definition, because */61 for the seconds field is not allowed, as far as I know. I did a test and tried */61 and *.75 for the seconds field, and it seems to execute every 60 seconds.

So we'll need to be strict in this and enforce that the duration has to be <= 60 seconds, or if bigger than 60 seconds, it has to be a multiple of 60 seconds up to 60*60 (3600 seconds = 60 minutes, i.e. 1, 2, 3... 60 minutes), and from then on, a multiple of hours.
